### ISSUE TITLE
`FileIO` and `Type` classes using global `Index.config`

### ISSUE THREAD

**Issue by mico** [relaton/relaton-index#9]
Using global `Index.config` will make it impossible to use `relaton-index` simultaneously for several `relaton-*` gems.

@andrew2net could you confirm if that a real issue?

**Comment by andrew2net** [comment]
@mico `Index.config` has 3 settings: `storage`, `storage_dir`, and `filename`. The `storage` and `storage_dir` settings are global. The `filename` is usually redefined in `relaton-*` gems with
```ruby
index = Relaton::Index.find_or_create :IHO, file: "index-v2.yaml"
```
I don't see any issue here.

**Comment by ronaldtse** [comment]
Thanks @andrew2net for the clarification. Can we have this in documentation on how to use `Relaton::Index`? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse we have this in the documentation https://github.com/relaton/relaton-index#configuration
These global settings are created for the possibility of using this gem in an AWS Lambda container. Since Lambda can't save files inside a container we can implement and exploit another storage class, for example, `S3Storage`. So these settings aren't helpful for users who run this gem on local comp.
